// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IntegrationMachineModelDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AlternativeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternativeName { get; set; }
#nullable restore
#else
        public string AlternativeName { get; set; }
#endif
        /// <summary>The DisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The IsActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The MachineType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineTypeDto? MachineType { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineTypeDto MachineType { get; set; }
#endif
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ProductNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductNumber { get; set; }
#nullable restore
#else
        public string ProductNumber { get; set; }
#endif
        /// <summary>The Supplier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationSupplierDto? Supplier { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationSupplierDto Supplier { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineModelDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineModelDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineModelDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AlternativeName", n => { AlternativeName = n.GetStringValue(); } },
                { "DisplayName", n => { DisplayName = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "IsActive", n => { IsActive = n.GetBoolValue(); } },
                { "MachineType", n => { MachineType = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineTypeDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineTypeDto.CreateFromDiscriminatorValue); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "ProductNumber", n => { ProductNumber = n.GetStringValue(); } },
                { "Supplier", n => { Supplier = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationSupplierDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationSupplierDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AlternativeName", AlternativeName);
            writer.WriteStringValue("DisplayName", DisplayName);
            writer.WriteIntValue("Id", Id);
            writer.WriteBoolValue("IsActive", IsActive);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationMachineTypeDto>("MachineType", MachineType);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("ProductNumber", ProductNumber);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationSupplierDto>("Supplier", Supplier);
        }
    }
}
#pragma warning restore CS0618
