// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InvoiceViewDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The DefaultEmploymentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultEmploymentId { get; set; }
#nullable restore
#else
        public string DefaultEmploymentId { get; set; }
#endif
        /// <summary>The DefaultStoreId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultStoreId { get; set; }
#nullable restore
#else
        public string DefaultStoreId { get; set; }
#endif
        /// <summary>The Employees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceEmploymentDto>? Employees { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceEmploymentDto> Employees { get; set; }
#endif
        /// <summary>The Jobs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto>? Jobs { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto> Jobs { get; set; }
#endif
        /// <summary>The JobStatusId property</summary>
        public int? JobStatusId { get; set; }
        /// <summary>The NoInvoice property</summary>
        public bool? NoInvoice { get; set; }
        /// <summary>The OrderDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceDetailDto>? OrderDetails { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceDetailDto> OrderDetails { get; set; }
#endif
        /// <summary>The OrderStatus property</summary>
        public int? OrderStatus { get; set; }
        /// <summary>The Participants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceUserDto>? Participants { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceUserDto> Participants { get; set; }
#endif
        /// <summary>The Primary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto? Primary { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto Primary { get; set; }
#endif
        /// <summary>The Samtech property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto? Samtech { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto Samtech { get; set; }
#endif
        /// <summary>The Stores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceStoreDto>? Stores { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceStoreDto> Stores { get; set; }
#endif
        /// <summary>The TimeZone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.TimeSpanObject? TimeZone { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.TimeSpanObject TimeZone { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceViewDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceViewDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceViewDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DefaultEmploymentId", n => { DefaultEmploymentId = n.GetStringValue(); } },
                { "DefaultStoreId", n => { DefaultStoreId = n.GetStringValue(); } },
                { "Employees", n => { Employees = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceEmploymentDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceEmploymentDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "JobStatusId", n => { JobStatusId = n.GetIntValue(); } },
                { "Jobs", n => { Jobs = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "NoInvoice", n => { NoInvoice = n.GetBoolValue(); } },
                { "OrderDetails", n => { OrderDetails = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceDetailDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceDetailDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "OrderStatus", n => { OrderStatus = n.GetIntValue(); } },
                { "Participants", n => { Participants = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceUserDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceUserDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Primary", n => { Primary = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto.CreateFromDiscriminatorValue); } },
                { "Samtech", n => { Samtech = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto.CreateFromDiscriminatorValue); } },
                { "Stores", n => { Stores = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceStoreDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceStoreDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "TimeZone", n => { TimeZone = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.TimeSpanObject>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.TimeSpanObject.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("DefaultEmploymentId", DefaultEmploymentId);
            writer.WriteStringValue("DefaultStoreId", DefaultStoreId);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceEmploymentDto>("Employees", Employees);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto>("Jobs", Jobs);
            writer.WriteIntValue("JobStatusId", JobStatusId);
            writer.WriteBoolValue("NoInvoice", NoInvoice);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceDetailDto>("OrderDetails", OrderDetails);
            writer.WriteIntValue("OrderStatus", OrderStatus);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceUserDto>("Participants", Participants);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceJobDto>("Primary", Primary);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto>("Samtech", Samtech);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.InvoiceStoreDto>("Stores", Stores);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.TimeSpanObject>("TimeZone", TimeZone);
        }
    }
}
#pragma warning restore CS0618
