// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SamtechDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The DefaultWorkArticle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultWorkArticle { get; set; }
#nullable restore
#else
        public string DefaultWorkArticle { get; set; }
#endif
        /// <summary>The GpsVehicles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.GpsVehicleDto>? GpsVehicles { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.GpsVehicleDto> GpsVehicles { get; set; }
#endif
        /// <summary>The SamtechGpsUrlbase property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SamtechGpsUrlbase { get; set; }
#nullable restore
#else
        public string SamtechGpsUrlbase { get; set; }
#endif
        /// <summary>The SamtechName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SamtechName { get; set; }
#nullable restore
#else
        public string SamtechName { get; set; }
#endif
        /// <summary>The SamtechPw property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SamtechPw { get; set; }
#nullable restore
#else
        public string SamtechPw { get; set; }
#endif
        /// <summary>The SamtechUser property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SamtechUser { get; set; }
#nullable restore
#else
        public string SamtechUser { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.SamtechDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DefaultWorkArticle", n => { DefaultWorkArticle = n.GetStringValue(); } },
                { "GpsVehicles", n => { GpsVehicles = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.GpsVehicleDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.GpsVehicleDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "SamtechGpsUrlbase", n => { SamtechGpsUrlbase = n.GetStringValue(); } },
                { "SamtechName", n => { SamtechName = n.GetStringValue(); } },
                { "SamtechPw", n => { SamtechPw = n.GetStringValue(); } },
                { "SamtechUser", n => { SamtechUser = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("DefaultWorkArticle", DefaultWorkArticle);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.GpsVehicleDto>("GpsVehicles", GpsVehicles);
            writer.WriteStringValue("SamtechGpsUrlbase", SamtechGpsUrlbase);
            writer.WriteStringValue("SamtechName", SamtechName);
            writer.WriteStringValue("SamtechPw", SamtechPw);
            writer.WriteStringValue("SamtechUser", SamtechUser);
        }
    }
}
#pragma warning restore CS0618
