// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Qwips.Integration.ClientSdk.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Qwips.Integration.ClientSdk.Api2.Integration.Machine.SerialNumberSearch {
    /// <summary>
    /// Builds and executes requests for operations under \api2\Integration\Machine\SerialNumberSearch
    /// </summary>
    public class SerialNumberSearchRequestBuilder : BaseRequestBuilder {
        /// <summary>
        /// Instantiates a new SerialNumberSearchRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SerialNumberSearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/Integration/Machine/SerialNumberSearch{?serialNumber*,includeInactive*,limit*}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new SerialNumberSearchRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SerialNumberSearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api2/Integration/Machine/SerialNumberSearch{?serialNumber*,includeInactive*,limit*}", rawUrl) {
        }
        /// <summary>
        /// Get machine list, based on SerialNumber.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<IntegrationMachineDto>?> GetAsync(Action<SerialNumberSearchRequestBuilderGetRequestConfiguration>? requestConfiguration = default, CancellationToken cancellationToken = default) {
#nullable restore
#else
        public async Task<List<IntegrationMachineDto>> GetAsync(Action<SerialNumberSearchRequestBuilderGetRequestConfiguration> requestConfiguration = default, CancellationToken cancellationToken = default) {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<IntegrationMachineDto>(requestInfo, IntegrationMachineDto.CreateFromDiscriminatorValue, default, cancellationToken);
            return collectionResult?.ToList();
        }
        /// <summary>
        /// Get machine list, based on SerialNumber.
        /// </summary>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<SerialNumberSearchRequestBuilderGetRequestConfiguration>? requestConfiguration = default) {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<SerialNumberSearchRequestBuilderGetRequestConfiguration> requestConfiguration = default) {
#endif
            var requestInfo = new RequestInformation {
                HttpMethod = Method.GET,
                UrlTemplate = UrlTemplate,
                PathParameters = PathParameters,
            };
            requestInfo.Headers.Add("Accept", "application/json;odata.metadata=minimal;odata.streaming=true");
            if (requestConfiguration != null) {
                var requestConfig = new SerialNumberSearchRequestBuilderGetRequestConfiguration();
                requestConfiguration.Invoke(requestConfig);
                requestInfo.AddQueryParameters(requestConfig.QueryParameters);
                requestInfo.AddRequestOptions(requestConfig.Options);
                requestInfo.AddHeaders(requestConfig.Headers);
            }
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public SerialNumberSearchRequestBuilder WithUrl(string rawUrl) {
            return new SerialNumberSearchRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get machine list, based on SerialNumber.
        /// </summary>
        public class SerialNumberSearchRequestBuilderGetQueryParameters {
            /// <summary>Option to include machines that have existed, but then later where manually deactivated.</summary>
            public bool? IncludeInactive { get; set; }
            /// <summary>The default result limited is 50 items, it can be changed here if needed.The limit is here to reduce the the server load.</summary>
            public int? Limit { get; set; }
            /// <summary>The serial number can be partial by using &apos;%&apos;, when no &apos;%&apos; are provided it will look for perfect matches.This parameter is case insensitive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? SerialNumber { get; set; }
#nullable restore
#else
            public string SerialNumber { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        public class SerialNumberSearchRequestBuilderGetRequestConfiguration {
            /// <summary>Request headers</summary>
            public RequestHeaders Headers { get; set; }
            /// <summary>Request options</summary>
            public IList<IRequestOption> Options { get; set; }
            /// <summary>Request query parameters</summary>
            public SerialNumberSearchRequestBuilderGetQueryParameters QueryParameters { get; set; } = new SerialNumberSearchRequestBuilderGetQueryParameters();
            /// <summary>
            /// Instantiates a new SerialNumberSearchRequestBuilderGetRequestConfiguration and sets the default values.
            /// </summary>
            public SerialNumberSearchRequestBuilderGetRequestConfiguration() {
                Options = new List<IRequestOption>();
                Headers = new RequestHeaders();
            }
        }
    }
}
