// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AllowPublicView property</summary>
        public bool? AllowPublicView { get; set; }
        /// <summary>The Comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comments { get; set; }
#nullable restore
#else
        public string Comments { get; set; }
#endif
        /// <summary>The CreditLimit property</summary>
        public double? CreditLimit { get; set; }
        /// <summary>The CreditLimitExceeded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditLimitExceeded { get; set; }
#nullable restore
#else
        public string CreditLimitExceeded { get; set; }
#endif
        /// <summary>The CustomerNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerNumber { get; set; }
#nullable restore
#else
        public string CustomerNumber { get; set; }
#endif
        /// <summary>The DeliveryAdressCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressCity { get; set; }
#nullable restore
#else
        public string DeliveryAdressCity { get; set; }
#endif
        /// <summary>The DeliveryAdressCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressCountry { get; set; }
#nullable restore
#else
        public string DeliveryAdressCountry { get; set; }
#endif
        /// <summary>The DeliveryAdressName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressName { get; set; }
#nullable restore
#else
        public string DeliveryAdressName { get; set; }
#endif
        /// <summary>The DeliveryAdressOptional1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressOptional1 { get; set; }
#nullable restore
#else
        public string DeliveryAdressOptional1 { get; set; }
#endif
        /// <summary>The DeliveryAdressOptional2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressOptional2 { get; set; }
#nullable restore
#else
        public string DeliveryAdressOptional2 { get; set; }
#endif
        /// <summary>The DeliveryAdressStreet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressStreet { get; set; }
#nullable restore
#else
        public string DeliveryAdressStreet { get; set; }
#endif
        /// <summary>The DeliveryAdressZip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryAdressZip { get; set; }
#nullable restore
#else
        public string DeliveryAdressZip { get; set; }
#endif
        /// <summary>The FreeFromVat property</summary>
        public bool? FreeFromVat { get; set; }
        /// <summary>The Id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The InvoiceDueDays property</summary>
        public int? InvoiceDueDays { get; set; }
        /// <summary>The InvoiceParentCustomer property</summary>
        public bool? InvoiceParentCustomer { get; set; }
        /// <summary>The IsActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The Latitude property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Latitude { get; set; }
#nullable restore
#else
        public string Latitude { get; set; }
#endif
        /// <summary>The Longitude property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Longitude { get; set; }
#nullable restore
#else
        public string Longitude { get; set; }
#endif
        /// <summary>The MailAdressCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailAdressCity { get; set; }
#nullable restore
#else
        public string MailAdressCity { get; set; }
#endif
        /// <summary>The MailAdressCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailAdressCountry { get; set; }
#nullable restore
#else
        public string MailAdressCountry { get; set; }
#endif
        /// <summary>The MailAdressStreet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailAdressStreet { get; set; }
#nullable restore
#else
        public string MailAdressStreet { get; set; }
#endif
        /// <summary>The MailAdressZip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailAdressZip { get; set; }
#nullable restore
#else
        public string MailAdressZip { get; set; }
#endif
        /// <summary>The Modified property</summary>
        public DateTimeOffset? Modified { get; set; }
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The OrganisationNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganisationNumber { get; set; }
#nullable restore
#else
        public string OrganisationNumber { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AllowPublicView", n => { AllowPublicView = n.GetBoolValue(); } },
                { "Comments", n => { Comments = n.GetStringValue(); } },
                { "CreditLimit", n => { CreditLimit = n.GetDoubleValue(); } },
                { "CreditLimitExceeded", n => { CreditLimitExceeded = n.GetStringValue(); } },
                { "CustomerNumber", n => { CustomerNumber = n.GetStringValue(); } },
                { "DeliveryAdressCity", n => { DeliveryAdressCity = n.GetStringValue(); } },
                { "DeliveryAdressCountry", n => { DeliveryAdressCountry = n.GetStringValue(); } },
                { "DeliveryAdressName", n => { DeliveryAdressName = n.GetStringValue(); } },
                { "DeliveryAdressOptional1", n => { DeliveryAdressOptional1 = n.GetStringValue(); } },
                { "DeliveryAdressOptional2", n => { DeliveryAdressOptional2 = n.GetStringValue(); } },
                { "DeliveryAdressStreet", n => { DeliveryAdressStreet = n.GetStringValue(); } },
                { "DeliveryAdressZip", n => { DeliveryAdressZip = n.GetStringValue(); } },
                { "FreeFromVat", n => { FreeFromVat = n.GetBoolValue(); } },
                { "Id", n => { Id = n.GetStringValue(); } },
                { "InvoiceDueDays", n => { InvoiceDueDays = n.GetIntValue(); } },
                { "InvoiceParentCustomer", n => { InvoiceParentCustomer = n.GetBoolValue(); } },
                { "IsActive", n => { IsActive = n.GetBoolValue(); } },
                { "Latitude", n => { Latitude = n.GetStringValue(); } },
                { "Longitude", n => { Longitude = n.GetStringValue(); } },
                { "MailAdressCity", n => { MailAdressCity = n.GetStringValue(); } },
                { "MailAdressCountry", n => { MailAdressCountry = n.GetStringValue(); } },
                { "MailAdressStreet", n => { MailAdressStreet = n.GetStringValue(); } },
                { "MailAdressZip", n => { MailAdressZip = n.GetStringValue(); } },
                { "Modified", n => { Modified = n.GetDateTimeOffsetValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "OrganisationNumber", n => { OrganisationNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AllowPublicView", AllowPublicView);
            writer.WriteStringValue("Comments", Comments);
            writer.WriteDoubleValue("CreditLimit", CreditLimit);
            writer.WriteStringValue("CreditLimitExceeded", CreditLimitExceeded);
            writer.WriteStringValue("CustomerNumber", CustomerNumber);
            writer.WriteStringValue("DeliveryAdressCity", DeliveryAdressCity);
            writer.WriteStringValue("DeliveryAdressCountry", DeliveryAdressCountry);
            writer.WriteStringValue("DeliveryAdressName", DeliveryAdressName);
            writer.WriteStringValue("DeliveryAdressOptional1", DeliveryAdressOptional1);
            writer.WriteStringValue("DeliveryAdressOptional2", DeliveryAdressOptional2);
            writer.WriteStringValue("DeliveryAdressStreet", DeliveryAdressStreet);
            writer.WriteStringValue("DeliveryAdressZip", DeliveryAdressZip);
            writer.WriteBoolValue("FreeFromVat", FreeFromVat);
            writer.WriteStringValue("Id", Id);
            writer.WriteIntValue("InvoiceDueDays", InvoiceDueDays);
            writer.WriteBoolValue("InvoiceParentCustomer", InvoiceParentCustomer);
            writer.WriteBoolValue("IsActive", IsActive);
            writer.WriteStringValue("Latitude", Latitude);
            writer.WriteStringValue("Longitude", Longitude);
            writer.WriteStringValue("MailAdressCity", MailAdressCity);
            writer.WriteStringValue("MailAdressCountry", MailAdressCountry);
            writer.WriteStringValue("MailAdressStreet", MailAdressStreet);
            writer.WriteStringValue("MailAdressZip", MailAdressZip);
            writer.WriteDateTimeOffsetValue("Modified", Modified);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("OrganisationNumber", OrganisationNumber);
        }
    }
}
#pragma warning restore CS0618
