// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IntegrationJobDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Appointments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto>? Appointments { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto> Appointments { get; set; }
#endif
        /// <summary>The ClosedDate property</summary>
        public DateTimeOffset? ClosedDate { get; set; }
        /// <summary>The CompletedDate property</summary>
        public DateTimeOffset? CompletedDate { get; set; }
        /// <summary>The CreatedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The CreatedDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The Customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto? Customer { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto Customer { get; set; }
#endif
        /// <summary>The CustomerComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerComment { get; set; }
#nullable restore
#else
        public string CustomerComment { get; set; }
#endif
        /// <summary>The CustomerDeliveryAdressCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerDeliveryAdressCity { get; set; }
#nullable restore
#else
        public string CustomerDeliveryAdressCity { get; set; }
#endif
        /// <summary>The CustomerDeliveryAdressCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerDeliveryAdressCountry { get; set; }
#nullable restore
#else
        public string CustomerDeliveryAdressCountry { get; set; }
#endif
        /// <summary>The CustomerDeliveryAdressName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerDeliveryAdressName { get; set; }
#nullable restore
#else
        public string CustomerDeliveryAdressName { get; set; }
#endif
        /// <summary>The CustomerDeliveryAdressStreet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerDeliveryAdressStreet { get; set; }
#nullable restore
#else
        public string CustomerDeliveryAdressStreet { get; set; }
#endif
        /// <summary>The CustomerDeliveryAdressZip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerDeliveryAdressZip { get; set; }
#nullable restore
#else
        public string CustomerDeliveryAdressZip { get; set; }
#endif
        /// <summary>The DisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The EstimatedTime property</summary>
        public double? EstimatedTime { get; set; }
        /// <summary>The FirstLineComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstLineComment { get; set; }
#nullable restore
#else
        public string FirstLineComment { get; set; }
#endif
        /// <summary>The Flag property</summary>
        public int? Flag { get; set; }
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The InverseParent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationChildJobDto>? InverseParent { get; set; }
#nullable restore
#else
        public List<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationChildJobDto> InverseParent { get; set; }
#endif
        /// <summary>The InvoiceComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceComment { get; set; }
#nullable restore
#else
        public string InvoiceComment { get; set; }
#endif
        /// <summary>The InvoiceReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceReference { get; set; }
#nullable restore
#else
        public string InvoiceReference { get; set; }
#endif
        /// <summary>The InvoiceReference2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceReference2 { get; set; }
#nullable restore
#else
        public string InvoiceReference2 { get; set; }
#endif
        /// <summary>The InvoiceReference3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceReference3 { get; set; }
#nullable restore
#else
        public string InvoiceReference3 { get; set; }
#endif
        /// <summary>The JobStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobStatusDto? JobStatus { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobStatusDto JobStatus { get; set; }
#endif
        /// <summary>The JobSubStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobSubStatusDto? JobSubStatus { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobSubStatusDto JobSubStatus { get; set; }
#endif
        /// <summary>The JobType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobTypeDto? JobType { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobTypeDto JobType { get; set; }
#endif
        /// <summary>The Modified property</summary>
        public DateTimeOffset? Modified { get; set; }
        /// <summary>The NoInvoice property</summary>
        public bool? NoInvoice { get; set; }
        /// <summary>The Order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.OrderDto? Order { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.OrderDto Order { get; set; }
#endif
        /// <summary>The PlannedDate property</summary>
        public DateTimeOffset? PlannedDate { get; set; }
        /// <summary>The ServiceManagerComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceManagerComment { get; set; }
#nullable restore
#else
        public string ServiceManagerComment { get; set; }
#endif
        /// <summary>The TechnicianComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TechnicianComment { get; set; }
#nullable restore
#else
        public string TechnicianComment { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationJobDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationJobDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationJobDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Appointments", n => { Appointments = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ClosedDate", n => { ClosedDate = n.GetDateTimeOffsetValue(); } },
                { "CompletedDate", n => { CompletedDate = n.GetDateTimeOffsetValue(); } },
                { "CreatedBy", n => { CreatedBy = n.GetStringValue(); } },
                { "CreatedDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "Customer", n => { Customer = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto.CreateFromDiscriminatorValue); } },
                { "CustomerComment", n => { CustomerComment = n.GetStringValue(); } },
                { "CustomerDeliveryAdressCity", n => { CustomerDeliveryAdressCity = n.GetStringValue(); } },
                { "CustomerDeliveryAdressCountry", n => { CustomerDeliveryAdressCountry = n.GetStringValue(); } },
                { "CustomerDeliveryAdressName", n => { CustomerDeliveryAdressName = n.GetStringValue(); } },
                { "CustomerDeliveryAdressStreet", n => { CustomerDeliveryAdressStreet = n.GetStringValue(); } },
                { "CustomerDeliveryAdressZip", n => { CustomerDeliveryAdressZip = n.GetStringValue(); } },
                { "DisplayName", n => { DisplayName = n.GetStringValue(); } },
                { "EstimatedTime", n => { EstimatedTime = n.GetDoubleValue(); } },
                { "FirstLineComment", n => { FirstLineComment = n.GetStringValue(); } },
                { "Flag", n => { Flag = n.GetIntValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "InverseParent", n => { InverseParent = n.GetCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationChildJobDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationChildJobDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "InvoiceComment", n => { InvoiceComment = n.GetStringValue(); } },
                { "InvoiceReference", n => { InvoiceReference = n.GetStringValue(); } },
                { "InvoiceReference2", n => { InvoiceReference2 = n.GetStringValue(); } },
                { "InvoiceReference3", n => { InvoiceReference3 = n.GetStringValue(); } },
                { "JobStatus", n => { JobStatus = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobStatusDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "JobSubStatus", n => { JobSubStatus = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobSubStatusDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobSubStatusDto.CreateFromDiscriminatorValue); } },
                { "JobType", n => { JobType = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobTypeDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobTypeDto.CreateFromDiscriminatorValue); } },
                { "Modified", n => { Modified = n.GetDateTimeOffsetValue(); } },
                { "NoInvoice", n => { NoInvoice = n.GetBoolValue(); } },
                { "Order", n => { Order = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.OrderDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.OrderDto.CreateFromDiscriminatorValue); } },
                { "PlannedDate", n => { PlannedDate = n.GetDateTimeOffsetValue(); } },
                { "ServiceManagerComment", n => { ServiceManagerComment = n.GetStringValue(); } },
                { "TechnicianComment", n => { TechnicianComment = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto>("Appointments", Appointments);
            writer.WriteDateTimeOffsetValue("ClosedDate", ClosedDate);
            writer.WriteDateTimeOffsetValue("CompletedDate", CompletedDate);
            writer.WriteStringValue("CreatedBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("CreatedDate", CreatedDate);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.CustomerDto>("Customer", Customer);
            writer.WriteStringValue("CustomerComment", CustomerComment);
            writer.WriteStringValue("CustomerDeliveryAdressCity", CustomerDeliveryAdressCity);
            writer.WriteStringValue("CustomerDeliveryAdressCountry", CustomerDeliveryAdressCountry);
            writer.WriteStringValue("CustomerDeliveryAdressName", CustomerDeliveryAdressName);
            writer.WriteStringValue("CustomerDeliveryAdressStreet", CustomerDeliveryAdressStreet);
            writer.WriteStringValue("CustomerDeliveryAdressZip", CustomerDeliveryAdressZip);
            writer.WriteStringValue("DisplayName", DisplayName);
            writer.WriteDoubleValue("EstimatedTime", EstimatedTime);
            writer.WriteStringValue("FirstLineComment", FirstLineComment);
            writer.WriteIntValue("Flag", Flag);
            writer.WriteIntValue("Id", Id);
            writer.WriteCollectionOfObjectValues<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationChildJobDto>("InverseParent", InverseParent);
            writer.WriteStringValue("InvoiceComment", InvoiceComment);
            writer.WriteStringValue("InvoiceReference", InvoiceReference);
            writer.WriteStringValue("InvoiceReference2", InvoiceReference2);
            writer.WriteStringValue("InvoiceReference3", InvoiceReference3);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobStatusDto>("JobStatus", JobStatus);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobSubStatusDto>("JobSubStatus", JobSubStatus);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.JobTypeDto>("JobType", JobType);
            writer.WriteDateTimeOffsetValue("Modified", Modified);
            writer.WriteBoolValue("NoInvoice", NoInvoice);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.OrderDto>("Order", Order);
            writer.WriteDateTimeOffsetValue("PlannedDate", PlannedDate);
            writer.WriteStringValue("ServiceManagerComment", ServiceManagerComment);
            writer.WriteStringValue("TechnicianComment", TechnicianComment);
        }
    }
}
#pragma warning restore CS0618
