// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IntegrationCustomerDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAddressDto? Address { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAddressDto Address { get; set; }
#endif
        /// <summary>The Contact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationContactDto? Contact { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationContactDto Contact { get; set; }
#endif
        /// <summary>The CreditLimit property</summary>
        public double? CreditLimit { get; set; }
        /// <summary>The CreditLimitExceeded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditLimitExceeded { get; set; }
#nullable restore
#else
        public string CreditLimitExceeded { get; set; }
#endif
        /// <summary>The CustomerGroupNo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerGroupNo { get; set; }
#nullable restore
#else
        public string CustomerGroupNo { get; set; }
#endif
        /// <summary>The FreeFromVat property</summary>
        public bool? FreeFromVat { get; set; }
        /// <summary>The Id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The IsActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The Latitude property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Latitude { get; set; }
#nullable restore
#else
        public string Latitude { get; set; }
#endif
        /// <summary>The Longitude property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Longitude { get; set; }
#nullable restore
#else
        public string Longitude { get; set; }
#endif
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The OrganisationNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganisationNumber { get; set; }
#nullable restore
#else
        public string OrganisationNumber { get; set; }
#endif
        /// <summary>The ParentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationCustomerDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationCustomerDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationCustomerDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Address", n => { Address = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAddressDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAddressDto.CreateFromDiscriminatorValue); } },
                { "Contact", n => { Contact = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationContactDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationContactDto.CreateFromDiscriminatorValue); } },
                { "CreditLimit", n => { CreditLimit = n.GetDoubleValue(); } },
                { "CreditLimitExceeded", n => { CreditLimitExceeded = n.GetStringValue(); } },
                { "CustomerGroupNo", n => { CustomerGroupNo = n.GetStringValue(); } },
                { "FreeFromVat", n => { FreeFromVat = n.GetBoolValue(); } },
                { "Id", n => { Id = n.GetStringValue(); } },
                { "IsActive", n => { IsActive = n.GetBoolValue(); } },
                { "Latitude", n => { Latitude = n.GetStringValue(); } },
                { "Longitude", n => { Longitude = n.GetStringValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "OrganisationNumber", n => { OrganisationNumber = n.GetStringValue(); } },
                { "ParentId", n => { ParentId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAddressDto>("Address", Address);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationContactDto>("Contact", Contact);
            writer.WriteDoubleValue("CreditLimit", CreditLimit);
            writer.WriteStringValue("CreditLimitExceeded", CreditLimitExceeded);
            writer.WriteStringValue("CustomerGroupNo", CustomerGroupNo);
            writer.WriteBoolValue("FreeFromVat", FreeFromVat);
            writer.WriteStringValue("Id", Id);
            writer.WriteBoolValue("IsActive", IsActive);
            writer.WriteStringValue("Latitude", Latitude);
            writer.WriteStringValue("Longitude", Longitude);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("OrganisationNumber", OrganisationNumber);
            writer.WriteStringValue("ParentId", ParentId);
        }
    }
}
#pragma warning restore CS0618
