// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IntegrationAppointmentDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AppointmentDate property</summary>
        public DateTimeOffset? AppointmentDate { get; set; }
        /// <summary>The AppointmentStatus property</summary>
        public int? AppointmentStatus { get; set; }
        /// <summary>The EndTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The ExchangeUniqueId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeUniqueId { get; set; }
#nullable restore
#else
        public string ExchangeUniqueId { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The JobId property</summary>
        public int? JobId { get; set; }
        /// <summary>The Participant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationParticipantDto? Participant { get; set; }
#nullable restore
#else
        public global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationParticipantDto Participant { get; set; }
#endif
        /// <summary>The StartTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The Subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The Type property</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationAppointmentDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AppointmentDate", n => { AppointmentDate = n.GetDateTimeOffsetValue(); } },
                { "AppointmentStatus", n => { AppointmentStatus = n.GetIntValue(); } },
                { "EndTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "ExchangeUniqueId", n => { ExchangeUniqueId = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "JobId", n => { JobId = n.GetIntValue(); } },
                { "Participant", n => { Participant = n.GetObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationParticipantDto>(global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationParticipantDto.CreateFromDiscriminatorValue); } },
                { "StartTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "Subject", n => { Subject = n.GetStringValue(); } },
                { "Type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("AppointmentDate", AppointmentDate);
            writer.WriteIntValue("AppointmentStatus", AppointmentStatus);
            writer.WriteDateTimeOffsetValue("EndTime", EndTime);
            writer.WriteStringValue("ExchangeUniqueId", ExchangeUniqueId);
            writer.WriteIntValue("Id", Id);
            writer.WriteIntValue("JobId", JobId);
            writer.WriteObjectValue<global::Qwips.ServiceSystem.Integration.ClientSdk.Models.IntegrationParticipantDto>("Participant", Participant);
            writer.WriteDateTimeOffsetValue("StartTime", StartTime);
            writer.WriteStringValue("Subject", Subject);
            writer.WriteIntValue("Type", Type);
        }
    }
}
#pragma warning restore CS0618
