// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Qwips.ServiceSystem.Integration.ClientSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Active property</summary>
        public bool? Active { get; set; }
        /// <summary>The AllowImportExport property</summary>
        public bool? AllowImportExport { get; set; }
        /// <summary>The EmailAdress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAdress { get; set; }
#nullable restore
#else
        public string EmailAdress { get; set; }
#endif
        /// <summary>The Id property</summary>
        public int? Id { get; set; }
        /// <summary>The IsTechnician property</summary>
        public bool? IsTechnician { get; set; }
        /// <summary>The Mobile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mobile { get; set; }
#nullable restore
#else
        public string Mobile { get; set; }
#endif
        /// <summary>The Modified property</summary>
        public DateTimeOffset? Modified { get; set; }
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The Uiculture property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uiculture { get; set; }
#nullable restore
#else
        public string Uiculture { get; set; }
#endif
        /// <summary>The UserLogonName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserLogonName { get; set; }
#nullable restore
#else
        public string UserLogonName { get; set; }
#endif
        /// <summary>The UserTypeId property</summary>
        public int? UserTypeId { get; set; }
        /// <summary>The VechicleId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VechicleId { get; set; }
#nullable restore
#else
        public string VechicleId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Qwips.ServiceSystem.Integration.ClientSdk.Models.UserDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Qwips.ServiceSystem.Integration.ClientSdk.Models.UserDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Qwips.ServiceSystem.Integration.ClientSdk.Models.UserDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Active", n => { Active = n.GetBoolValue(); } },
                { "AllowImportExport", n => { AllowImportExport = n.GetBoolValue(); } },
                { "EmailAdress", n => { EmailAdress = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetIntValue(); } },
                { "IsTechnician", n => { IsTechnician = n.GetBoolValue(); } },
                { "Mobile", n => { Mobile = n.GetStringValue(); } },
                { "Modified", n => { Modified = n.GetDateTimeOffsetValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "Uiculture", n => { Uiculture = n.GetStringValue(); } },
                { "UserLogonName", n => { UserLogonName = n.GetStringValue(); } },
                { "UserTypeId", n => { UserTypeId = n.GetIntValue(); } },
                { "VechicleId", n => { VechicleId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("Active", Active);
            writer.WriteBoolValue("AllowImportExport", AllowImportExport);
            writer.WriteStringValue("EmailAdress", EmailAdress);
            writer.WriteIntValue("Id", Id);
            writer.WriteBoolValue("IsTechnician", IsTechnician);
            writer.WriteStringValue("Mobile", Mobile);
            writer.WriteDateTimeOffsetValue("Modified", Modified);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("Uiculture", Uiculture);
            writer.WriteStringValue("UserLogonName", UserLogonName);
            writer.WriteIntValue("UserTypeId", UserTypeId);
            writer.WriteStringValue("VechicleId", VechicleId);
        }
    }
}
#pragma warning restore CS0618
